### ISSUE TITLE
Issue when openning app

### ISSUE THREAD

**Issue by FilipeOS** [delay/flutter_firebase_auth_example#3]
Hi @delay ,

I get this issue when I execute your code, I only removed the lastName and changed to `Navigator.push` the screens:
```
I/flutter (21732): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (21732): The following NoSuchMethodError was thrown building HomeScreen(dirty, state:
I/flutter (21732): _HomeScreenState#537ff):
I/flutter (21732): The getter 'data' was called on null.
I/flutter (21732): Receiver: null
I/flutter (21732): Tried calling: data
I/flutter (21732): 
I/flutter (21732): When the exception was thrown, this was the stack:
I/flutter (21732): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
I/flutter (21732): #1      StateWidget.of (package:flutter_app/util/state_widget.dart:34:10)
I/flutter (21732): #2      _HomeScreenState.build (package:flutter_app/ui/screens/home.dart:32:28)
I/flutter (21732): #3      StatefulElement.build (package:flutter/src/widgets/framework.dart:3825:27)
I/flutter (21732): #4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3739:15)
I/flutter (21732): #5      Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (21732): #6      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (21732): #7      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
I/flutter (21732): #8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (21732): #9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (21732): #10     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (21732): #11     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter (21732): #12     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (21732): #13     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (21732): #14     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (21732): #15     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (21732): #16     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (21732): #17     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (21732): #18     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (21732): #19     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (21732): #20     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter (21732): #21     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (21732): #22     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (21732): #23     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter (21732): #24     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (21732): #25     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (21732): #26     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter (21732): #27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (21732): #28     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (21732): #29     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter (21732): #30     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (21732): #31     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (21732): #32     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (21732): #33     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (21732): #34     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (21732): #35     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
I/flutter (21732): #36     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (21732): #37     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (21732): #38     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (21732): #39     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (21732): #40     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (21732): #41     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (21732): #42     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (21732): #43     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (21732): #44     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (21732): #45     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (21732): #46     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (21732): #47     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (21732): #48     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
I/flutter (21732): #49     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (21732): #50     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (21732): #51     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (21732): #52     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter (21732): #53     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (21732): #54     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (21732): #55     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (21732): #56     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (21732): #57     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (21732): #58     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (21732): #59     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (21732): #60     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (21732): #61     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter (21732): #62     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (21732): #63     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (21732): #64     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (21732): #65     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (21732): #66     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (21732): #67     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
I/flutter (21732): #68     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (21732): #69     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (21732): #70     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (21732): #71     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (21732): #72     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (21732): #73     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (21732): #74     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (21732): #75     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (21732): #76     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (21732): #77     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter (21732): #78     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (21732): #79     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (21732): #80     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (21732): #81     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (21732): #82     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (21732): #83     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (21732): #84     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (21732): #85     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (21732): #86     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (21732): #87     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (21732): #88     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (21732): #89     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
I/flutter (21732): #90     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (21732): #91     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (21732): #92     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (21732): #93     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (21732): #94     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (21732): #95     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (21732): #96     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
I/flutter (21732): #97     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (21732): #98     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (21732): #99     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4982:32)
I/flutter (21732): #100    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (21732): #101    Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (21732): #102    _TheatreElement.mount (package:flutter/src/widgets/overlay.dart:593:16)
I/flutter (21732): #103    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (21732): #104    Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (21732): #105    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (21732): #106    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (21732): #107    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (21732): #108    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
I/flutter (21732): #109    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (21732): #110    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (21732): #111    Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (21732): #112    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (21732): #113    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (21732): #114    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (21732): #115    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (21732): #116    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (21732): #117    Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (21732): #118    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter (21732): #119    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (21732): #120    Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (21732): #121    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (21732): #122    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (21732): #123    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (21732): #124    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
I/flutter (21732): #125    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (21732): #126    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (21732): #127    Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (21732): #128    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter (21732): #129    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (21732): #130    Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (21732): #131    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter (21732): #132    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (21732): #133    Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (21732): #134    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (21732): #135    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (21732): #136    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (21732): #137    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
I/flutter (21732): #138    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (21732): #139    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (21732): #140    Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (21732): #141    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (21732): #142    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (21732): #143    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (21732): #144    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (21732): #145    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (21732): #146    Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (21732): #147    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (21732): #148    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (21732): #149    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (21732): #150    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (21732): #151    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (21732): #152    Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (21732): #153    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (21732): #154    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (21732): #155    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (21732): #156    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (21732): #157    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (21732): #158    Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (21732): #159    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (21732): #160    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (21732): #161    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (21732): #162    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (21732): #163    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (21732): #164    Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (21732): #165    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (21732): #166    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (21732): #167    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (21732): #168    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (21732): #169    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (21732): #170    Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (21732): #171    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (21732): #172    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (21732): #173    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (21732): #174    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (21732): #175    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (21732): #176    Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (21732): #177    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (21732): #178    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (21732): #179    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (21732): #180    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
I/flutter (21732): #181    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (21732): #182    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (21732): #183    Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (21732): #184    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (21732): #185    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (21732): #186    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (21732): #187    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (21732): #188    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (21732): #189    Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (21732): #190    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (21732): #191    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (21732): #192    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (21732): #193    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (21732): #194    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (21732): #195    Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (21732): #196    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (21732): #197    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (21732): #198    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (21732): #199    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (21732): #200    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (21732): #201    Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (21732): #202    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (21732): #203    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (21732): #204    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (21732): #205    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (21732): #206    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (21732): #207    Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (21732): #208    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (21732): #209    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (21732): #210    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (21732): #211    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (21732): #212    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (21732): #213    Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (21732): #214    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter (21732): #215    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (21732): #216    Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (21732): #217    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (21732): #218    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (21732): #219    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (21732): #220    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
I/flutter (21732): #221    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (21732): #222    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (21732): #223    Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (21732): #224    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (21732): #225    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (21732): #226    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (21732): #227    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (21732): #228    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (21732): #229    Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (21732): #230    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (21732): #231    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (21732): #232    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (21732): #233    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
I/flutter (21732): #234    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (21732): #235    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (21732): #236    Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (21732): #237    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (21732): #238    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (21732): #239    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (21732): #240    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (21732): #241    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (21732): #242    Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (21732): #243    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (21732): #244    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (21732): #245    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (21732): #246    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
I/flutter (21732): #247    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (21732): #248    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (21732): #249    Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (21732): #250    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (21732): #251    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (21732): #252    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (21732): #253    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (21732): #254    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (21732): #255    Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (21732): #256    RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:933:16)
I/flutter (21732): #257    RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:904:5)
I/flutter (21732): #258    RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:850:17)
I/flutter (21732): #259    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2258:19)
I/flutter (21732): #260    RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:849:13)
I/flutter (21732): #261    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:736:7)
I/flutter (21732): #262    runApp (package:flutter/src/widgets/binding.dart:780:7)
I/flutter (21732): #263    main (package:flutter_app/main.dart:15:3)
I/flutter (21732): #265    main (package:flutter_app/main.dart:14:10)
I/flutter (21732): #266    _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:199:25)
I/flutter (21732): #271    _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:190:5)
I/flutter (21732): #272    _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:300:19)
I/flutter (21732): #273    _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
I/flutter (21732): (elided 5 frames from package dart:async and package dart:async-patch)
I/flutter (21732): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by delay** [comment]
not really sure what might be missing from the error message.  Did you install the firebase app code when setting up your project?

**Comment by FilipeOS** [comment]
Hi @delay,

I had my code working fine with firebase email/password and google but I liked more your code and placed the entire /lib folder with the .yaml dependencies and made the proper renaming of the files but nothing structural so I don't understand why it's giving null.

Your StateModel is null on /home.dart and it's throwing that error because it's not getting any data.

**Comment by delay** [comment]
Maybe check your main.dart and double check your wrapping your state in the main() function.  That might be why state is returning null.
